FROM ubuntu:20.04
ENV J_URL 127.0.0.1:8080
ENV J_USR admin
ENV J_PSW admin
ENV J_LABELS swarm
ENV J_SWARM_VERSION 3.24
RUN apt update && apt install -y openjdk-11-jdk  apt-transport-https ca-certificates curl software-properties-common wget
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN add-apt-repository "deb https://download.docker.com/linux/ubuntu focal stable"
RUN apt install -y docker-ce

RUN wget https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/${J_SWARM_VERSION}/swarm-client-${J_SWARM_VERSION}.jar
CMD java -jar swarm-client-${J_SWARM_VERSION}.jar -master http://${J_URL} -username ${J_USR} -password ${J_PSW} -labels "${J_LABELS}" -executors 2
